    backend:
      name: github
      branch: decap # Branch to update (optional; defaults to master)
      repo: kamilaaliima/teste-doc
      preview_context: my-provider/deployment
    

    # These lines should *not* be indented
    media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
    public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

    collections:
      - name: doc
        label: "documentação"
        folder: kamilaaliima/doc
        identifier_field: kamilaaliima
        extension: md
        widget: "documentação"
        create: true
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        fields:
          - { name: Doc, label: documento, widget: string }
          - { name: body, label: Body, widget: markdown }
          - { label: "Language", name: "language" }

